spring.application.name=plantapp

server.port=8081

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.dcdqmtzbjxztoajpaelw
spring.datasource.password=DB82_J!pass12

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# =========================
# CONNECTION POOL (IMPORTANT)
# =========================
spring.datasource.hikari.maximum-pool-size=5